apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-hqv3
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0020-tenant/tkrw-pr712-0075-0020-app/devfile-sample-hqv3@sha256:017aa22d24f6615490effd45d3d6730e4b74a0bfc201379460c62c127c5b6114
        name: my-nodejs
        resources: {}
status: {}
